"""Dual PDF generation — Customer Quotation + Factory Production Package."""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import quote


def export_pdf_bytes(builder_name: str, payload: Mapping[str, Any]) -> bytes:
    if builder_name == "factory":
        return build_factory_pdf_bytes(payload)
    return build_customer_pdf_bytes(payload)


def export_pdf(payload: Mapping[str, Any], path: str | Path, *, kind: str = "customer") -> Path:
    path = Path(path)
    path.write_bytes(export_pdf_bytes(kind, payload))
    return path


def build_quote_pdf_bytes(payload: Mapping[str, Any]) -> bytes:
    """Back-compat alias → customer quotation."""
    return build_customer_pdf_bytes(payload)


def build_customer_pdf_bytes(payload: Mapping[str, Any]) -> bytes:
    try:
        return _customer_reportlab(payload)
    except Exception:
        return _minimal_text_pdf("WEOS Customer Quotation", payload)


def build_factory_pdf_bytes(payload: Mapping[str, Any]) -> bytes:
    try:
        return _factory_reportlab(payload)
    except Exception:
        return _minimal_text_pdf("WEOS Factory Package", payload)


def _qr_png(data: str, box_size: int = 4) -> bytes | None:
    try:
        import qrcode

        img = qrcode.make(data)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()
    except Exception:
        return None


def _customer_reportlab(payload: Mapping[str, Any]) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    y = H - 40

    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, y, "WEOS — Quotation")
    y -= 16
    c.setFont("Helvetica", 9)
    c.setFillColorRGB(0.35, 0.35, 0.35)
    c.drawString(40, y, "Design • Calculate • Manufacture • Quote")
    c.setFillColorRGB(0, 0, 0)
    y -= 22

    c.setFont("Helvetica", 10)
    c.drawString(40, y, f"Project: {payload.get('projectId', '')}   Quotation: {payload.get('quotationId', '')}")
    y -= 14
    c.drawString(40, y, f"Customer: {payload.get('customer') or '—'}   Name: {payload.get('name') or '—'}")
    y -= 22

    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Line items")
    y -= 16
    c.setFont("Helvetica", 9)
    for line in payload.get("lines") or []:
        if y < 80:
            c.showPage()
            y = H - 50
            c.setFont("Helvetica", 9)
        desc = f"{line.get('displayName')}  {line.get('width')}×{line.get('height')} mm  ×{line.get('qty')}"
        amt = (line.get("price") or {}).get("total", 0)
        c.drawString(40, y, desc[:70])
        c.drawRightString(W - 40, y, f"₹ {amt}")
        y -= 12
        opts = line.get("options") or {}
        c.setFillColorRGB(0.4, 0.4, 0.4)
        c.drawString(50, y, f"Glass: {opts.get('glass')}  Colour: {opts.get('colour')}  Handle: {opts.get('handle')}")
        c.setFillColorRGB(0, 0, 0)
        y -= 14

    y -= 8
    cats = (payload.get("price") or {}).get("categoryTotals") or (payload.get("combined") or {}).get("categoryTotals") or {}
    c.setFont("Helvetica-Bold", 10)
    for cat, total in cats.items():
        c.drawString(40, y, f"{cat}")
        c.drawRightString(W - 40, y, f"₹ {total}")
        y -= 14

    grand = (payload.get("price") or {}).get("total") or (payload.get("combined") or {}).get("grandTotal")
    y -= 6
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, y, "Grand Total")
    c.drawRightString(W - 40, y, f"₹ {grand}")
    y -= 28

    c.setFont("Helvetica", 8)
    c.drawString(40, y, "Warranty: 1 year manufacturing defects (demo terms).")
    y -= 12
    c.drawString(40, y, "Terms: 50% advance, balance before dispatch. Rates excl. site installation unless noted.")
    y -= 12
    c.drawString(40, y, "Generated by WEOS — Window Engineering Operating System.")

    c.showPage()
    c.save()
    return buf.getvalue()


def _factory_reportlab(payload: Mapping[str, Any]) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    y = H - 40
    qid = payload.get("quotationId") or payload.get("projectId") or "WEOS"
    pid = payload.get("projectId", "")

    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, y, "WEOS — Factory Production Package")
    y -= 18
    c.setFont("Helvetica", 10)
    c.drawString(40, y, f"Production ID / Quotation: {qid}")
    y -= 14
    c.drawString(40, y, f"Project: {pid}")
    y -= 8

    # QR code linking project/quotation id
    qr_data = f"weos://production/{quote(str(qid), safe='')}?project={quote(str(pid), safe='')}"
    qr_png = _qr_png(qr_data)
    if qr_png:
        img = ImageReader(io.BytesIO(qr_png))
        c.drawImage(img, W - 120, H - 120, width=70, height=70, mask="auto")
        c.setFont("Helvetica", 7)
        c.drawRightString(W - 40, H - 128, "Scan → production")

    y -= 20
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Glass sizes")
    y -= 14
    c.setFont("Helvetica", 8)
    for line in payload.get("lines") or []:
        for g in line.get("glass") or []:
            if y < 60:
                c.showPage()
                y = H - 50
            c.drawString(40, y, f"{g.get('qty')} pcs  {g.get('width')}×{g.get('height')}×{g.get('thicknessMm')} mm  ({line.get('displayName')})")
            y -= 11

    y -= 8
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Hardware (rolled)")
    y -= 14
    c.setFont("Helvetica", 8)
    for h in (payload.get("combined") or {}).get("hardwareRolled") or []:
        if y < 60:
            c.showPage()
            y = H - 50
        c.drawString(40, y, f"{h.get('name')}: {h.get('qty')}")
        y -= 11

    y -= 8
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Cut list")
    y -= 14
    c.setFont("Helvetica", 8)
    for line in payload.get("lines") or []:
        for cut in line.get("cutList") or []:
            if y < 60:
                c.showPage()
                y = H - 50
            c.drawString(
                40,
                y,
                f"{cut.get('profile')}: {cut.get('length_mm')} mm × {cut.get('quantity')}  ∠{cut.get('cut_angle')}",
            )
            y -= 11

    opt = payload.get("optimization") or {}
    if opt:
        y -= 10
        if y < 100:
            c.showPage()
            y = H - 50
        c.setFont("Helvetica-Bold", 11)
        c.drawString(40, y, "Optimization report")
        y -= 14
        c.setFont("Helvetica", 8)
        alu = opt.get("aluminium") or {}
        gl = opt.get("glass") or {}
        c.drawString(40, y, f"Aluminium: {alu.get('newBars')} new bars, waste {alu.get('wastePercent')}%, leftovers used {len(alu.get('leftoversUsed') or [])}")
        y -= 11
        c.drawString(40, y, f"Glass: {gl.get('sheetsNeeded')} sheets, waste {gl.get('wastePercent')}%")
        y -= 14
        c.setFont("Helvetica-Bold", 10)
        c.drawString(40, y, "Purchase list")
        y -= 12
        c.setFont("Helvetica", 8)
        for p in opt.get("purchaseList") or []:
            c.drawString(40, y, f"{p.get('qty')} × {p.get('item')}")
            y -= 11

    y -= 16
    c.setFont("Helvetica", 8)
    c.drawString(40, y, "No marketing content — machine-ready factory data only.")
    c.showPage()
    c.save()
    return buf.getvalue()


def _minimal_text_pdf(title: str, payload: Mapping[str, Any]) -> bytes:
    price = payload.get("price") or {}
    text = f"{title}\\nProject: {payload.get('projectId')}\\nQuote: {payload.get('quotationId')}\\nTotal: {price.get('total', 0)}"
    content = f"BT /F1 12 Tf 50 750 Td ({text}) Tj ET"
    objects = [
        "1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n",
        "2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n",
        "3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R >> >> >>endobj\n",
        f"4 0 obj<< /Length {len(content)} >>stream\n{content}\nendstream\nendobj\n",
        "5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for obj in objects:
        offsets.append(len(out))
        out.extend(obj.encode("latin-1"))
    xref = len(out)
    out.extend(f"xref\n0 {len(offsets)}\n".encode("latin-1"))
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(f"{off:010d} 00000 n \n".encode("latin-1"))
    out.extend(f"trailer<< /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode("latin-1"))
    return bytes(out)
